#!/bin/bash -e

./cps_api_db_unittest -a
./cps_api_events_unittest -a
./cps_api_operation_unittest -a
./cps_api_key_unittest -a
./cps_class_map_unittest -a
./cps_api_key_cache_unittest -a
./cps_api_registration_unittest -a
