/**
 * filename: ds_acl_qualifier_mask_union.h
 * (c) Copyright 2014 Dell Inc. All Rights Reserved.
 **/

/** OPENSOURCELICENSE */

/* DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 */
#ifndef __DS_ACL_QUALIFIER_MASK_UNION_H__
#define __DS_ACL_QUALIFIER_MASK_UNION_H__

/**
 * Union holding all acl valmask structs
 */
typedef union {

  ds_acl_valmask32_t valmask32;              /* Generic Valmask struct holding uint32_t types */
  ds_acl_valmask16_t valmask16;              /* Generic Valmask struct holding uint16_t types */  
  ds_acl_valmask8_t valmask8;                /* Generic Valmask struct holding uint8_t types */
  ds_acl_macinfo_valmask_t macinfo_valmask;  /* Generic Valmask struct holding mac addr types */
  ds_acl_ipaddr_valmask_t ipaddr_valmask;    /* IPv4 Address */
  ds_acl_ip6addr_valmask_t ip6addr_valmask;  /* IPv6 Address */

} ds_acl_qualifier_mask_t;

#endif
