/**
 * filename: ds_acl_action.h
 * (c) Copyright 2014 Dell Inc. All Rights Reserved.
 **/

/** OPENSOURCELICENSE */

/* DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 */

#ifndef __DS_ACL_ACTION_H__
#define __DS_ACL_ACTION_H__

/**
 * Enum holding acl action types
 */

typedef enum {

ds_acl_PERMIT,                  /* Permit packet matching rule */
ds_acl_DENY,                    /* Drop */
ds_acl_REDIRECT,                /* Redirect Packet */
ds_acl_PKT_PRIO,                /* Internal priority for setting new priority */
ds_acl_COPY_TO_CPU,             /* Copy to CPU */
ds_acl_COPY_TO_CPU_CANCEL,      /* Override rule - COPY_TO_CPU */
ds_acl_SWITCH_TO_CPU_CANCEL,    /* Override switch logic COPY_TO_CPU */
ds_acl_COSQ_CPU_NEW,            /* Change CoS Queue when CopyToCpu */
ds_acl_DROP_PRECEDENCE,         /* Set Drop Precedence */
ds_acl_METER_CONFIG,            /* Meter configuration */
ds_acl_RP_DROP_PRECEDENCE,      /* Set Red Priority Drop Precision */
ds_acl_YP_DROP_PRECEDENCE,      /* Set Yellow Priority Drop Precision */
ds_acl_SWITCH_CANCEL,           /* Override another rule */
ds_acl_PBRREDIRECT,             /* Redirect packet*/
ds_acl_COSQ_NEW,                /* Change CoS Queue */
ds_acl_RP_DROP,                 /* Red Priority Drop */
ds_acl_REDIRECT_IPMC,           /* Replace L3 multicast L3 & L2 bitmap */
ds_acl_ECN_NEW,                 /* Change ECN value in IP header TOS */
ds_acl_CLASS_TAG,               /* Add Classification Tag */
ds_acl_REDIRECT_VLAN,           /* Redirect to VLAN port bitmap */
ds_acl_CLASS_DEST,              /* Set destination address lookup class id */
ds_acl_REDIRECT_TRUNK,          /* Redirect Packet to a trunk */
ds_acl_REDIRECT_PBMP,           /* Replace port bitmap */
ds_acl_SRCMAC_NEW,              /* Replace source mac of the packet */
ds_acl_DSTMAC_NEW,              /* Replace destination mac of the packet */
ds_acl_OUTERVLAN_NEW,           /* Replace outer VLAN ID */
ds_acl_OUTERVLANPCP_NEW,        /* Replace outer VLAN PCP */
ds_acl_DSCP_NEW,                /* Change DSCP value */
ds_acl_EGRESS_PORTS_ADD,        /* Add additional egress ports */
ds_acl_CLASS_DEST_SET,          /* Set destination address lookup class id */
ds_acl_CLASS_SRC_SET,           /* Set source address lookup class id*/
ds_acl_L3_CHANGE_MAC_DA,        /* Change Destination mac address */
ds_acl_EGRESS_MASK,             /* Apply egress mask */
ds_acl_REDIRECT_MCAST,          /* Replace L2 multicast dest bitmap */
ds_acl_MIRROR,                  /* Mirror Packet */
ds_acl_MIRROR_INGRESS,          /* Ingress mirror */
ds_acl_MIRROR_EGRESS,           /* Egress mirror */
ds_acl_MIRROR_OVERRIDE,         /* Override any mirroring for packet */
ds_acl_REDIRECT_L2MC,           /* Redirect L2 Multicast*/
ds_acl_ACTION_COUNT             /* Always Last. Not a usable value.*/

}ds_acl_action_enum_t;

#endif

