/**
 * filename: ds_acl_qualifier.h
 * (c) Copyright 2014 Dell Inc. All Rights Reserved.
 **/

/* OPENSOURCELICENSE */


/* DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 */

#ifndef __DS_ACL_QUALIFIER_H__
#define __DS_ACL_QUALIFIER_H__

/**
 * Enum holding acl qualifier types
 */


typedef enum {

ds_acl_SRC_MAC,                     /* Source L2 MAC Address */
ds_acl_DST_MAC,                     /* Destination L2 MAC Address */
ds_acl_ETHER_TYPE,                  /* Ethernet Type */
ds_acl_COLOR,                       /* Packet color */
ds_acl_OUTER_VLAN,                  /* Outer VLAN */
ds_acl_INTERFACE_CLASS_L2,          /* Vlan Class Id */
ds_acl_L2_STATION_MOVE,             /* L2 Source port mismatch */
ds_acl_ING_STP_STATE,               /* Ingress Vlan STG STP state */
ds_acl_FORWARDING_VLAN_VALID,       /* Forwarding vlan is valid */
ds_acl_IP_SRC,                      /* Source IPv4 Addres */
ds_acl_IP_DST,                      /* Destination IPv4 Address*/
ds_acl_IP_TYPE,                     /* IP Type */
ds_acl_IP_PROTOCOL,                 /* IP Protocol Field */
ds_acl_IP_FRAG,                     /* IP Fragment info */
ds_acl_IP_FLAGS,                    /* IPv4 Flags */
ds_acl_IP_TTL,                      /* Time To Live/Hop Limit */
ds_acl_DSCP,                        /* Diffserv Code Point */
ds_acl_ICMP_TYPE_CODE,              /* ICMP Type codes */
ds_acl_IN_PORT,                     /* Single Input Port */
ds_acl_IN_PORTS,                    /* Input Ports */
ds_acl_OUT_PORT,                    /* Single Output Port */
ds_acl_SRC_L4_PORT,                 /* TCP/UDP Source Port */
ds_acl_DST_L4_PORT,                 /* TCP/UDP Destination Port */
ds_acl_TCP_CONTROL,                 /* TCP Control Flags */
ds_acl_TUNNEL_TYPE,                 /* Tunnel Type */
ds_acl_PACKET_RES,                  /* Packet Resolution Values */
ds_acl_QUALIFIER_COUNT              /* Always Last. Not a usable value.*/

}ds_acl_qualifier_enum_t;

#endif

