
#ifndef CPS_API_INC_PRIVATE_CPS_API_METADATA_IMPORT_H_
#define CPS_API_INC_PRIVATE_CPS_API_METADATA_IMPORT_H_


#define CPS_API_METADATA_ENV "CPS_API_METADATA_PATH"

void cps_api_metadata_import(void);


#endif /* CPS_API_INC_PRIVATE_CPS_API_METADATA_IMPORT_H_ */
