DN_SCRIPTS:=	$(wildcard lib/yang_tools/py/*.py) \
				$(wildcard lib/yang_tools/*.sh) \
				$(wildcard lib/*.py) \
				$(wildcard lib/cpsmetadata/*.xml) \
				$(wildcard bin/*)

include ${MAKE_INC}/workspace.mak
