
CFG_FILES:=$(wildcard init/*)

DN_SCRIPTS:=	$(wildcard lib/yang_tools/py/*.py) \
				$(wildcard lib/yang_tools/*.sh) \
				$(wildcard lib/*.py) \
				$(wildcard bin/*)

include ${MAKE_INC}/workspace.mak
