PROGRAMS=
SUBDIRS=
LIBRARIES= db_common
ARCHIVES=
HEADERS=$(wildcard inc/*)

db_common_SRCS=db_common_list.cpp db_interface_common.cpp db_operation_common.cpp

include ${PROJROOT}/tools/workspace.mak

